spring:
  datasource:
    url: jdbc:mysql://localhost:3306/subway?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  sql:
    init:
      mode: always
